# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c94fd5c7b83f3f1720cf8d194208a762"
name = "Taskfy"
handle = "taskfy"
application_url = "https://companion-subjects-side-wendy.trycloudflare.com"
embedded = true

[api]
api_version = "2025-04"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_discounts,write_products,read_customers,write_customers,write_files,read_files"

[auth]
redirect_urls = [
  "https://companion-subjects-side-wendy.trycloudflare.com/auth/callback",
  "https://companion-subjects-side-wendy.trycloudflare.com/auth/shopify/callback",
  "https://companion-subjects-side-wendy.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "wuwus-sklep.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true
