api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "taskfy-advanced-discounts"
type = "function"
discount_classes = ["ORDER", "PRODUCT", "SHIPPING"]

description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
  export = "cart-delivery-options-discounts-generate-run"

  [extensions.input.variables]
  namespace = "$app:discount"
  key = "input-variables"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
